### ISSUE TITLE
Icon change: WAVES

### ISSUE THREAD

**Issue by spasma** [cjdowner/cryptocurrency-icons#38]
Waves had an updated logo: https://twitter.com/wavesplatform
Actually, it's a square on it's side 😄 

Love your icon set! Keep up the good work!

**Comment by cjdowner** [comment]
Revolutionary. 😂 Fixed in the latest update. https://github.com/cjdowner/cryptocurrency-icons/commit/62d1b64467bc27c882333f4578346bffddde6df2

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
