### ISSUE TITLE
Sprite sheet

### ISSUE THREAD

**Issue by cjdowner** [cjdowner/cryptocurrency-icons#49]
Link #46 

Please comment below if you would like this. This will be a lot of overhead to maintain when new icons are added...

**Comment by gallisiardi** [comment]
You can indicate in the readme the possibility to create a sprite, but I think it is better that everyone creates their own sprites according to their needs (related to the size of the icons). It depends a lot on the size that the icons must have in publication. If you are quick to generate the 16x16 icon set for your export process, you might consider adding that format. Otherwise, each one generates the format optimized for its use.

**Comment by lunaroyster** [comment]
Perhaps a script could generate a sprite sheet automatically from the SVG icons. That would get rid of the overhead, as we could auto-generate them with travis-ci when somebody pushes to master.
