### ISSUE TITLE
Known issues Dec 9

### ISSUE THREAD

**Issue by cjdowner** [cjdowner/cryptocurrency-icons#8]
Missing icons
- [ ] Syscoin
- [x] Nexus
- [x] ATMChain
- [x] PowerLedger #13
- [x] Cryptonex
- [ ] ChainLink

To improve
- [ ] Dragonchain

**Comment by BlakeWilliams** [comment]
Can you add REQ (request.network) to the list as well?

Also, thanks for putting this together!

**Comment by cjdowner** [comment]
@BlakeWilliams Added!

**Comment by PTBKoo** [comment]
I noticed AdEx svg version doesn't seem to work. 

Can you also add ICON (ICX). Recently became one of the top 20 coins. 

Love the svg icons! Thanks

**Comment by PTBKoo** [comment]
It seems because it has the word 'ad' in it my ublock was blocking AdEx icons from loading. After white listing it works fine.

**Comment by cjdowner** [comment]
@PTBKoo ICX token added https://github.com/cjdowner/cryptocurrency-icons/commit/8077a46fe25c61c62cf026c5803e9b0eebe53bd5

**Comment by danieldraper** [comment]
Hello,

Really nice work with the icons. I have a couple of missing icons/issues.

**Issues**
- [ ] The icon for [0x](https://coinmarketcap.com/currencies/0x/) is called 0x instead of the symbol ZRX

**Missing Icons**
- [ ] [Dent (DENT)](https://coinmarketcap.com/currencies/dent/)
- [ ] [Gas (GAS)](https://coinmarketcap.com/currencies/gas/)
- [ ] [aelf (ELF)](https://coinmarketcap.com/currencies/aelf/)
- [ ] [Cryptonex (CNX)](https://coinmarketcap.com/currencies/cryptonex/) (Already mentioned above)
- [ ] [Enigma (ENG)](https://coinmarketcap.com/currencies/enigma-project/)
- [ ] [BitBay (BAY)](https://coinmarketcap.com/currencies/bitbay/)
- [ ] [Ripio Credit Network (RCN)](https://coinmarketcap.com/currencies/ripio-credit-network/)

All these are currently in the top 100.

**Comment by cjdowner** [comment]
@danieldraper all addressed: https://github.com/cjdowner/cryptocurrency-icons/commit/a7c59e1f54db772316c7f767ed8fed70ee481865

**Comment by khuezy** [comment]
`req.png` doesn't exist in the non `svg` folder.

**Comment by cjdowner** [comment]
@khuezy whoops. Thanks for letting me know. Fixed https://github.com/cjdowner/cryptocurrency-icons/commit/dbc21e7406a8d075fa4d2241da74c43d4168b787
